import { Inter } from "next/font/google";
import "./globals.css";
import "./App.css";
import Navbar from "@/components/reuseable/Navbar/Navbar";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import StoreProvider from "@/redux/provider/StoreProvider.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={inter.className}>
          <Navbar />
          <div className="mt-[120px] sm:mt-[140px]">{children}</div>
        </body>
      </StoreProvider>
    </html>
  );
}
